### ISSUE TITLE
User POV - Landing Page

### ISSUE THREAD

**Issue by rrshahed** [rrshahed/travel#2]
### User Story
As a user, I want to find out all the important information to book my next desired trip.

### Tasks

- [ ] The landing page will have a background image on top, a search field that says "Going to?" another search field right below that says "Date?" and a search button below.

<img width="296" alt="image" src="https://github.com/rrshahed/travel/assets/12882532/9e5b93f9-152c-4df1-8ec3-81c635b8e3a2">

- [ ] Clicking on the **Going To** search field will show a list of popular destinations and also allow the user to type in their destination name. 

<img width="297" alt="image" src="https://github.com/rrshahed/travel/assets/12882532/7a4487e8-0176-4b9f-91df-b5d8380ca7a7">

- [ ] Clicking on the Date field will allow the user to select a range of dates.

<img width="300" alt="image" src="https://github.com/rrshahed/travel/assets/12882532/a37c1e9e-8222-4e9d-b030-6481bd641dea">
